spring:
  profiles:
    active: dev
  application:
    name: example-hippo4j-core
  cloud:
    nacos:
      config:
        # 服务端地址
        server-addr: 192.168.174.100:8848
        # 是否开启监听和自动刷新
        refresh-enabled: true
        # 声明从配置中心读取的文件格式
        file-extension: yaml
  config:
    import:
      - optional:nacos:example-hippo4j-core.yml
